---
title: "2026 New York and Pennsylvania Pest Management Guidelines for Grapes"
format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    page-layout: article
---

## Authors

**Bryan Brown**  
Cornell IPM, Cornell AgriTech, Geneva, NY  
*Weed management*

**Jessica Clippinger**  
Penn State University, North East, PA  
*Disease management*

**Katie Gold**  
Penn State University, Integrated Pest and Crop Management, Geneva, NY  
*Disease management*

**Bryan E. Hed**  
Penn State University, North East, PA  
*Disease management*

**Michael Helms**  
Cornell IPM Pesticide Safety Education Program, Ithaca, NY  
*Pesticide information*

**Greg Loeb**  
Department of Entomology, Geneva, NY  
*Entomology*

**Megan Luke**  
Penn State Cooperative Extension Erie County, Erie, PA  
*Pesticide information, pest management*

**Flor E. Acevedo**  
Department of Entomology, Penn State University, North East, PA  
*Entomology*

**Lynn Sosnoskie**  
School of Integrative Plant Science, Horticulture Section, Geneva, NY  
*Weed management*

## Acknowledgments

Special appreciation is extended to the following for their contributions to this publication:

**Terence R. Bates**  
Lake Erie Regional Grape Program, Portland, NY

**David Combs**  
School of Integrative Plant Sciences, Plant Pathology and Plant-Microbe Biology Section, Geneva, NY

**Amara Dunn**  
Biocontrol Specialist, Cornell IPM, Geneva, NY

**Rick Dunst** *(retired)*  
Lake Erie Regional Grape Program, Portland, NY

**David M. Gadoury**  
School of Integrative Plant Sciences, Plant Pathology and Plant-Microbe Biology Section, Geneva, NY

**Heather Leach**  
Department of Entomology, University Park, PA

**Andrew J. Landers** *(retired)*  
Department of Entomology, Geneva, NY

**Timothy E. Martinson** *(retired)*  
Cornell Cooperative Extension, Geneva NY

**Andrew J. Muza** *(retired)*  
Penn State Cooperative Extension – Erie County, Erie, PA

**Bruce I. Reisch** *(retired)*  
School of Integrative Plant Sciences, Horticulture Section, Geneva, NY

**Michael C. Saunders** *(retired)*  
Department of Entomology, University Park, PA

**Andrew F. Senesac** *(retired)*  
Cornell Cooperative Extension – Suffolk County, Riverhead, NY

**Jody Timer** *(retired)*  
Penn State University, North East, PA

**Hans C. Walter-Peterson**  
Finger Lakes Regional Grape Program, Penn Yan, NY

**Timothy H. Weigle** *(retired)*  
Cornell IPM, Portland, NY

**Alice V. Wise**  
Cornell Cooperative Extension – Suffolk County, Riverhead, NY

**Wayne F. Wilcox** *(retired)*  
School of Integrative Plant Sciences, Plant Pathology and Plant-Microbe Biology Section, Geneva, NY

## Abbreviations and Symbols Used in This Publication

| Abbreviation | Meaning                      | Abbreviation | Meaning                      | Abbreviation | Meaning                      |
|--------------|------------------------------|--------------|------------------------------|--------------|------------------------------|
| A            | acre                         | EC           | emulsifiable concentrate     | SP           | soluble powder               |
| AI           | active ingredient            | F            | flowable                     | UDH          | up to day of harvest         |
| AS           | aqueous suspension           | G            | granular                     | ULV          | ultra-low volume             |
| D            | dust                         | L            | liquid                       | W            | wettable                     |
| DF           | dry flowable                 | P            | pellets                      | WDG          | water-dispersible granule    |
| DG           | dispersible granule          | PHI          | pre-harvest interval         | WP           | wettable powder              |
| DTH          | days to harvest              | SC           | suspension concentrate       | WSP          | water soluble packet         |
| E            | emulsion, emulsifiable       |              |                              |              |                              |

| Symbol | Meaning                                                                           |
|--------|-----------------------------------------------------------------------------------|
| *      | Federal restricted use pesticide; may be purchased and used only by certified applicators |
| *NY    | Restricted use pesticide in New York State                                        |
| †      | Not for use in Nassau and Suffolk Counties                                        |
| ^      | Not registered for use in New York State at press time                            |



Every effort has been made to provide correct, complete, and up-to-date pest management information for New York State and Pennsylvania at the time this publication was released for printing (___ 2025). Changes in pesticide registrations, regulations, and guidelines occurring after publication are available in county cooperative extension offices or from the Cornell IPM Pesticide Safety Education Program (psep.cce.cornell.edu) or the Pennsylvania Department of Agriculture’s Bureau of Plant Industry (www.agriculture.state.pa.us).

Where trade names appear, no discrimination is intended, and no endorsement by Cornell Cooperative Extension or Penn State Cooperative Extension is implied.

**These guidelines are not a substitute for pesticide labeling. Always read and understand the product label before using any pesticide.**

The guidelines in this bulletin reflect the current (and past) authors’ best efforts to interpret a complex body of scientific research, and to translate this into practical management options. Following the guidance provided in this bulletin does not assure compliance with any applicable law, rule, regulation or standard, or the achievement of particular discharge levels from agricultural land.
