---
title: 1.7 Pesticide Recordkeeping/Reporting
date: 2026-01-21T15:34:00.000-05:00
---
## 1.7.1 New York State Reporting Requirements

**Manufacturers and importers.** The NYSDEC requires annual reports from pesticide manufacturers and importers documenting all restricted use product sales within the state. These records include the EPA Registration Number, container size, and number of containers sold to New York buyers. These records need to be maintained for at least three years.

**Point of sale reporting.** The NYSDEC requires annual reports from those selling or offering for sale restricted use pesticides to private applicators. The reports include each sale of a restricted or general use pesticide to a private applicator that’s used in agricultural crop production. Reports include the EPA Registration Number; name and quantity of the pesticide purchased; purchase date; and location of intended application by address (including zip code) or, if an address is unavailable, by town or city (including zip code). An annual report is required even if no pesticides were sold during the calendar year.

**Commercial applicators.** Commercial applicators and technicians are required to submit annual reports to the NYSDEC of their restricted and general use pesticide applications. These reports include the EPA Registration Number, product name and quantity used, date applied, and location of application by address (including zip code). All commercial applicators and technicians must file an annual report even if no pesticide applications were made during the calendar year.

## 1.7.2 New York State Recordkeeping Requirements

**Commercial applicators and technicians** must maintain corresponding application records of the dosage rates, methods of application, and target organisms. These records need to be maintained annually, retained for at least three years, and made available for inspection on request by the NYSDEC.

**Private applicators** are required to maintain records of the restricted use pesticides purchased and used. These records need to include, at a minimum: the restricted use pesticide(s) purchased; crop treated; application method, and date(s) of application(s). (A form meeting these requirements is available from the DEC online at [www.dec.ny.gov/docs/materials_minerals_pdf/privatercdfrm.pdf](http://www.dec.ny.gov/docs/materials_minerals_pdf/privatercdfrm.pdf). A copy of this form is at the back of this book.) Records need to be retained for at least three years and must be made available for inspection by the NYSDEC upon request.

More information on New York State reporting and recordkeeping requirements can be obtained from the NYSDEC in Albany at [518-402-8748](tel:518-402-8748) or [PestMgt@dec.ny.gov](mailto:PestMgt@dec.ny.gov).

## 1.7.3 Federal Private Applicator Recordkeeping Requirements

Federal regulations require private applicators to keep records of the *federally restricted use* pesticides they apply. Federally required records must contain the following:

* Applicator name;
* Applicator certification number;
* Month, day, and year of application;
* EPA Registration Number for product applied;
* Brand or product name of pesticide applied;
* Crop, commodity, or site treated;
* Size of area treated;
* Total amount of pesticide product applied; and
* Location of the application using any of the following:

  * County, range, township, and section;
  * Maps, GPS coordinates, or written descriptions;
  * A USDA identification system, which involves maps and a numbering system to identify field locations; or
  * The legal property description.

Under federal recordkeeping regulations, applications of a restricted use pesticide to less than 1/10 of an acre on the same day are defined as spot applications. Spot application records must include: month/day/year of application; brand or product name of pesticide applied; EPA registration number; total amount of pesticide applied; and location of the application designated as a “spot treatment” with a brief description. *NOTE:* Spot treatments do not apply to nurseries or greenhouses. Applications at these locations are recorded as if they are a non-spot application.

Federally required information must be recorded within 14 days of the application and be maintained for 2 years after the application. Access to federal record information is limited to: USDA-authorized representatives presenting identification; state-authorized representatives presenting identification; and attending licensed health care professionals (or those acting under their direction) when treating individuals who may have been exposed to a restricted use pesticide.
