---
title: 1.8 EPA Worker Protection Standard (WPS) for Agricultural Pesticides
date: 2026-01-21T15:34:00.000-05:00
---
The WPS is designed to reduce the risks of pesticide illness or injury to pesticide handlers and agricultural workers who work in the production of agricultural plants on farms, or in nurseries, greenhouses, and forests. Generally, WPS requirements include:

* Restricted-entry intervals (REIs) for agricultural pesticides.
* Personal protective equipment (PPE) for handlers and early-entry workers.
* Decontamination supplies and emergency assistance.
* Pesticide safety training and information sharing.
* Specific WPS instructions on pesticide labels.
* Application exclusion zones.

[A more complete discussion of the WPS can be found online at ](<>)[www.epa.gov/pesticide-worker-safety/
agricultural-worker-protection-standard-wps](https://www.epa.gov/pesticide-worker-safety/agricultural-worker-protection-standard-wps). You can also contact your [regional NYSDEC pesticide office](https://dec.ny.gov/about/contact-us/statewide-office-information) for more information.
