---
title: 2.2 Site Selection and Preparation
date: 2026-01-23T16:11:00.000-05:00
---
Preparations for a berry planting must begin one to two years in advance. Select a site with good air and water drainage and have a preplant soil and a nematode analysis performed on representative soil samples. *Growers may wish to select a more broad-spectrum approach to preplant soil analysis at this time by opting for a comprehensive Cornell soil health assessment.* 

::: {.api-insert endpoint="https://cropandpestguides.cce.cornell.edu/NewGuidelinesTableImportTest/api/example"}
<!-- api-cache -->

<!-- /api-cache -->
:::


Some Blank Text

```{=html}
<table style="border-collapse: collapse; width: 100%;" border="1"><colgroup><col style="width: 50%;"><col style="width: 50%;"></colgroup>
<tbody>
<tr>
<td>1</td>
<td>2</td>
</tr>
<tr>
<td>3</td>
<td>4</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
```

## 2.2.1 Basic Soil Test

Agro-One provides soil and nutrient testing services previously available through the Cornell Nutrient Analysis Laboratory along with additional analytical services. Key input regarding analytical methods and quality control is provided by Cornell, and Cornell nutrient management guidelines are provided by Cornell through DairyOne.

**Table 2.1.1. Conversion factors to convert from one unit to another.**

| To convert from              | To               | Multiply by |
| ---------------------------- | ---------------- | ----------- |
| lb/A                         | lb/100 sq ft     | 0.0023      |
| tn/A                         | lb/100 sq ft     | 4.6         |
| lb/A                         | kg/ha            | 1.12        |
| kg/ha                        | lb/A             | 0.893       |
| lb                           | oz               | 16          |
| qt of fruit                  | lb of fruit      | 1.5         |
| qt                           | pt               | 2           |
| pt                           | qt               | 0.5         |
| gal of liquid                | lb of liquid     | 8.3         |
| Strawberries                 |                  |             |
| lb/A                         | lb/100 ft of row | 0.008       |
| Yield in lb/100 ft of row    | lb/A             | 125         |
| Yield in qt/100 ft of row    | lb/A             | 188         |
| Raspberries and Blackberries |                  |             |
| lb/A                         | lb/100 ft of row | 0.013       |
| Yield in lb/100 ft of row    | lb/A             | 77          |
| Yield in qt/100 ft of row    | lb/A             | 116         |
| Blueberries                  |                  |             |
| lb/A                         | lb/100 ft of row | 0.018       |
| Yield in lb/100 ft of row    | lb/A             | 56          |
| Yield in qt/100 ft of row    | lb/A             | 84          |
| Currants and Gooseberries    |                  |             |
| lb/A                         | lb/100 ft of row | 0.005       |
| Yield in lb/100 ft of row    | lb/A             | 217         |
| Yield in qt/100 ft of row    | lb/A             | 325         |
| Grapes                       |                  |             |
| lb/A                         | lb/100 ft of row | 0.03        |
| Yield in lb/100 ft of row    | lb/A             | 33          |
| Yield in qt/100 ft of row    | lb/A             | 50          |

Obtain basic soil test instructions and sample boxes by contacting: Dairy One, 730 Warren Road, Ithaca, NY 14850 or calling 1-800-344-2697, or visiting <https://dairyone.com/services/agronomy-services/soil-analysis/>.

Be sure to indicate on the soil test submission form if the recommendations requested are for preplanting – recommendations will be different for an established planting. *Note: Boron is frequently low in fruit plantings throughout the Northeast.* *Boron testing is not included in most standard soil test packages and should be selected as an added test for berry soils*.

Please note: Soil test results differ from lab to lab, depending on the extraction technique used. Therefore, recommendations are lab-specific. Do not use values from one lab to determine recommendations from another. Some labs take a conservative approach to recommendations, while others want to ensure that the crop has a more than adequate nutrient reserve. Some labs provide a general soil recommendation for all crops, whereas others like Agro-One provide specific recommendations for specific crops using Cornell’s recommendation engine.

## 2.2.2 Cornell Soil Health Test

Soil health describes the capacity of a soil to be used productively without adversely affecting its future productivity, the ecosystem or the environment. Soil health emphasizes the integration of biological with chemical and physical measures of soil quality that affect farmers' profits and the environment.

Soil health deals with both inherent and dynamic soil quality. **Inherent soil quality** relates to the natural characteristics of the soil, such as its texture. These qualities are the result of soil-forming factors, are generally represented in soil surveys, and cannot be changed easily. 

In contrast, **dynamic soil quality** components, such as compaction, biological functioning, root proliferation, etc. are readily affected by management practices. The dynamic component is of most interest to growers because good management allows the soil to come to its full potential. 

The inherent and dynamic soil quality components do interact; however, as some soil types are much more susceptible to degradation and unforgiving of poor management than others.

Soil health is important to farmers and growers because they need to know if their soil will continue to sustain profitable yields, and to help reduce long-term risks to environmental quality.

The Cornell Soil Health Program Work Team has developed soil measurements to help monitor the state of soil health both in space and time. These indicators can measure soil improvement or degradation resulting from different management practices and also the long-term changes in soil health under given management practices. 

* A comprehensive soil health analysis package includes:
* Particle size distribution and texture
* Wet aggregate stability
* Available water capacity
* Surface hardness
* Subsurface hardness
* Organic matter
* Active carbon
* Soil respiration
* Soil protein
* Root pathogen pressure
* Standard fertility test and recommendations (pH, Modified Mehlich Buffer pH (lime requirement), organic matter and Modified Morgan extractable phosphorus, potassium, calcium, magnesium, aluminum, iron, zinc, and manganese.)

*Note: Hot water boron testing should be selected as add-on in addition to the Cornell soil health test assessment package*.

Due to seasonal variability in biological and physical indicators), all samples must be received between April 1 and June 15. 

For more information on the Cornell soil health test contact Bob Schindelbeck, 1003 Bradfield Hall, Cornell University, Ithaca, NY 14853-1901, or call (607) 227-6055 or visit: <http://soilhealth.cals.cornell.edu/>.

A series of webinars on soil and nutrient management in berry crops can be found here: <https://blogs.cornell.edu/berries/productions/berry-soil-and-nutrient-management-a-guide-for-educators-and-growers/>.

## 2.2.3 Nematodes

Nematodes are microscopic eel-shaped worms that live in soil and water. Most are beneficial organisms helping to break down soil organic matter and release soil nutrients. Others may cause both direct and indirect damage to berry crops by feeding on plant roots. Direct damage results from feeding on below ground plant parts. Indirect damage results from feeding wounds that provide entry sites for soil-borne fungal pathogens. Nematodes also are known to transmit numerous plant viruses.

The most common nematodes causing problems in berries are root lesion, northern root knot, and dagger nematodes.

Cultural management practices for nematodes include: 

1. Preventing introduction of nematodes to clean fields by thoroughly cleaning equipment between fields.
2. Rotation to non-host crops for 2 to 5 years.
3. Use of resistant varieties where available.
4. Use of nematode-suppressive cover crops such as brassicas, some sorghum-sudan grasses, marigolds.
5. Frequent tillage to expose root debris and subject nematodes to drying conditions.

Preplant fumigation may further reduce nematode numbers in soil.

## 2.2.4 Nematode Testing

Samples may be submitted for nematode testing to the Plant Disease Diagnostic Clinic, College of Agriculture and Life Sciences, Ithaca, NY. The best time for collecting samples for nematode testing is during the active growing season. A minimum of 6 soil subsamples, approx. 1” in diameter and 4” in depth should be collected randomly from an area approx. ½ acre in size. Gently mix samples together, transfer about 1 pint of mixed soil to a plastic bag. For best results, ship as soon as possible to the diagnostic lab. Refrigerate sample if it cannot be shipped immediately. For more information and fee schedules visit their website at [www.plantclinic.cornell.edu](http://www.plantclinic.cornell.edu/).

Follow the recommendations of the soil and nematode tests to ensure a good planting in future years. A nutritionally healthy planting in a well-drained soil with exposure to air movement is least susceptible to damage from pests. 

## 2.2.5 Garden Symphylans

Garden symphylans (sometimes called garden centipedes) are very small, thin white animals with 8 to 12 pairs of legs and very distinctive bead-like antennae. They inhabit soil, spending all of their life cycle underground in the dark. Symphylans feed on germinating vegetable and weed seeds, roots and root hairs of plants. Sometimes feeder roots are completely cut off by symphylan feeding; leaving brown stubs were the roots should be. Feeding on roots interferes with plant growth and yield, and causes plant stunting.

Damage may also lead to wilting on warm days and in some instances, plant death. Symphylans may chew holes in larger roots and strawberry fruit. Damage may also occur to above ground plant parts in contact with soil. Chewing injuries then become infection courts for soil-borne diseases.

Direct observation is probably the best method for determining the presence of symphylans in soil. Sample the top 6 to 12” of warm, moist soil prior to tillage. Gently place a shovel full of soil on a piece of black plastic. Break apart soil clumps and count numbers of symphylans present. Sample 10 to 20 shovels of soil per acre. A rule of thumb action threshold for symphylans is 5 to 20 per shovelful of soil for moderate to highly susceptible crops.

Cultural management practices for symphylans include:

1. Deep, thorough cultivation between crops to destroy earthworm tunnels, symphylans and eggs present, and crop rotation. Reports indicate 2 to 3 tillings per week for 3 to 4 weeks prior to planting have been recorded as being successful in reducing symphylan numbers.
2. Crop rotation. Populations have been demonstrated to decrease significantly following potato crops; allowing growth of a more susceptible crop afterwards. While no other cover crops reduce population numbers as much as potatoes, spring oats also showed reduced numbers. Conversely, numbers were higher following mustard and spinach crops.

Preplant fumigation may further reduce symphylan numbers in soil.
