---
title: 2.3 Fumigation
date: 2026-01-23T17:00:00.000-05:00
---
Fumigation may be required if nematode and/or symphylans levels are high or if pathogenic fungi (e.g. Phytophthora, Pythium, Rhizoctonia, and Fusarium) or insect pests are present in the soil. Fumigation may also provide some weed control. The grower can apply some types of fumigants; others must be commercially applied. Soil should be friable and moist prior to fumigation, and the soil temperature should be 50° to 90°F. All plant material must be decomposed prior to fumigation. See Table 2.3.1.

*Growers who fumigate their crops are requirements to have a detailed "Fumigant Management Plan" (FMP) in place before fumigating, and for at least two people at the fumigation site to have an appropriate respirator and be fit-tested and medically cleared to use one. Even growers who have their fumigation done by custom work will need an FMP specific to their farm.*

## 2.3.1 Soil Fumigant Management Plans

Soil fumigations are complex processes that require specialized equipment and practices to properly apply volatile and toxic pesticides. EPA's risk mitigation allows for site specific decisions to address the conditions where the fumigant is applied. To address this complexity and flexibility, EPA is requiring that fumigant users prepare a written, site-specific fumigant management plan (FMP) before fumigations begin. Written plans and procedures for safe and effective applications will help prevent accidents and misuse and will capture emergency response plans and steps to take in case an accident occurs.

Once the application begins, the certified applicator must make a copy of the FMP available for viewing by handlers involved in the fumigation. The certified applicator or the owner/operator of the application block must provide a copy of the FMP to any local/state/federal/tribal enforcement personnel who request the FMP. In the case of an emergency, the FMP must be made available when requested by local/state/federal/tribal emergency response and enforcement personnel.

**Table 2.3.1. Selected fumigants registered for use on fruit crops in NY State**

:::html-table {.raw-html}
<p>&nbsp;</p>
<table style="border-collapse: collapse; width: 100%; height: 157.344px;" border="1"><colgroup><col style="width: 25%;"><col style="width: 25%;"><col style="width: 25%;"><col style="width: 25%;"></colgroup>
<tbody>
<tr style="height: 33.375px;">
<td colspan="4"><strong>Table 2.3.1. Selected fumigants registered for use on fruit crops in NY State.</strong></td>
</tr>
<tr style="height: 34.4375px;">
<td><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Fumigant</span></strong></td>
<td><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Formulation</span></strong></td>
<td><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Rate/acre</span></strong></td>
<td><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">EPA Reg. No.</span></strong></td>
</tr>
<tr style="height: 34.4375px;">
<td><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">1,3 dichloropropene</span></strong></td>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">*&dagger;Telone II</span></td>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">27-35 gal</span></td>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">95290-1</span></td>
</tr>
<tr style="height: 55.0938px;">
<td colspan="4"><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Better, on cold, dry soils than most other fumigants. Control and/or suppression of diseases and nematodes, symphylans, and wireworms.</span></td>
</tr>
<tr>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><strong style="mso-bidi-font-weight: normal;">1,3 dichloropropene + chloropicrin</strong><br></span></td>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">*&dagger;Telone-C17<br></span></td>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">32.4-42 gal<br></span></td>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">62719-12<br></span></td>
</tr>
<tr>
<td colspan="4"><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Used as a preplant fumigant for strawberries. Control and/or suppression of soil-borne diseases and nematodes, symphylans, and wireworms.</span><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"><br></span></td>
</tr>
<tr>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">sodium methyl dithiocarbamate<br></span></td>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">*Vapam HL<br></span></td>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">37.5-75 gal<br></span></td>
<td><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">5481-468<br></span></td>
</tr>
<tr>
<td colspan="4"><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">May be applied by water-run applications (e.g., chemigation), soil injection or soil bedding equipment. Control and/or suppression of weeds, as Bermudagrass, Chickweed, Dandelion, Ragweed, Henbit, Lambsquarter, Pigweed, Watercress, Amaranthus species, Watergrass, Johnsongrass, Nightshade, Nutsedge, Wild Morning-Glory and Purslane, soil-borne diseases such as Rhizoctonia, Pythium, Phytophthora, Verticillium, Sclerotinia, Oak Root Fungus and Club Root of crucifers, nematodes, and symphylids.<br></span></td>
</tr>
<tr>
<td colspan="4">
<p class="MsoNormal" style="margin-top: 2.0pt;"><span style="font-size: 9.0pt; mso-bidi-font-size: 10.0pt;">* = Restricted-use pesticide. </span></p>
<p class="MsoNormal" style="margin-top: 2.0pt;"><span style="font-size: 9.0pt; mso-bidi-font-size: 10.0pt;">&dagger; = Not for use in Nassau and Suffolk Counties.</span></p>
<p class="MsoNormal" style="margin-top: 2.0pt;"><span style="font-size: 9.0pt; mso-bidi-font-size: 10.0pt;"><span style="font-size: 9.0pt; mso-bidi-font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">CAUTION: Vapors from all fumigants are harmful. Strictly follow cautions given on label.</span><span style="font-size: 10.0pt; font-family: 'Times New Roman',serif; mso-fareast-font-family: 'Times New Roman'; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;"> </span></span></p>
</td>
</tr>
</tbody>
</table>
<p><br><br></p>
:::

```{python}
#| echo: true
#| warning: false
#| message: false

import requests
from IPython.display import HTML, display

url = "https://cropandpestguides.cce.cornell.edu/NewGuidelinesTableImportTest/api/example"
html = requests.get(url, timeout=30).text
display(HTML(html))
```
