---
title: 2.5 Test Site
---
11111

Cornell University and Cornell Cooperative Extension actively promote the use of Integrated Crop and Pest Management (IPM) by New York growers in order to address agricultural concerns. In many areas of New York State, there are horticultural, economic, social, and political pressures to reduce the environmental impact and use of pesticides in crop production. Public concerns with nutrient and sediment movement into ground and surface water and pressure against pesticide applications is growing. In other regions, agricultural producers are being asked to submit nutrient and soil management plans to address the offsite impacts of their practices. In addition, the development of pesticide resistance in key pests; registration of fewer and more expensive new chemicals for pest control; loss of existing products; and increased competition from other regions continue to push New York agriculture to look for nonchemical alternatives.

## 2.5.1 Spotted Lanternfly

**Table 2.5.1 This is a Simple Test Table for Tree Fruit. It is for Spotted Lanternfly and a Test Crop.**

{{< pesticide-table guidelineId="1" pestId="402" siteId="84" >}}

Using GuidelineId: **Tree Fruit** (1), PestId: **Spotted Lanternfly** (402), SiteId: **Test Crop** (84)

## 2.5.1 Apple Scab

Apple scab fungicides can control disease through four different types of activity: protection, post-infection activity, presymptom activity, and postsymptom activity. Understanding these activities and knowing which fungicides exhibit them can help a grower determine the materials that are likely to give the best results under a certain set of conditions.

**Protection.** Protection refers to the ability of fungicide residues to kill or inactivate scab spores (and thereby prevent infection) when the residue is already on or in the leaf or fruit before the infection takes place. A good protective fungicide must exhibit satisfactory retention, that is, the fungicide residue must stick to the leaf surface or be retained within to resist excessive washing away of the deposits by rain. On the other hand, a good protective fungicide should also have good redistribution properties, that is, fungicide residues should have a tendency to be washed by rain and redeposited on previously unprotected tissue. Ideally, a fungicide should stick well enough not to be washed off the tree, but should be redistributed well enough during rains to protect new growth.

**Table 2.5.2 This is a Simple Test Table for Tree Fruit. It is for Apple Scab and a Test Crop.**

{{< pesticide-table guidelineId="1" pestId="15" siteId="84" >}}

Using GuidelineId: **Tree Fruit** (1), PestId: **Apple Scab** (15), SiteId: **Test Crop** (84)
