---
title: "5 Highbush Blueberries "
---
## 5.1 Introduction

Numerous pests affect highbush blueberries, although the pest complexis much narrower than with many other fruit crops. For photographs of thesepests and for detailed information on blueberry culture, obtain a copy of theHighbush Blueberry Production Guide (NRAES-55) from your Cornell CooperativeExtension Office or download a free fair use pdf copy (23.0 MB) of thispublication at: [http://www.hort.cornell.edu/fruit/berry-guides/ blueberry.pdf](http://www.hort.cornell.edu/fruit/%20berry-guides/%20blueberry.pdf). For approaches to organic pest management, download the 2021 Organic Production and IPM Guide for Blueberries at [https://ecommons.cornell.edu/handle/ 1813/42887.2](https://ecommons.cornell.edu/handle/1813/42887.2) For assistancewith diagnosing highbush blueberry problems, use the online Berry DiagnosticTool at: <https://blogs.cornell.edu/berrytool/>or contact your Cornell Cooperative Extension Office for assistance. 

To submit samples for disease diagnosis, contact PlantDisease Clinic, Cornell University, Plant Pathology section, 
SIPS, 334 Plant Science Building, Ithaca, NY 14853-4203, (607) 255-7850, onlineat: [plantclinic.cornell.edu](http://plantclinic.cornell.edu/). Tosubmit samples for insect diagnosis or for phone consultations, contact InsectDiagnostic Laboratory, Cornell University, Department of Entomology, 4140Comstock Hall, Ithaca, NY 14853-2601, (607) 255-3250, online at: [idl.entomology.cornell.edu](http://idl.entomology.cornell.edu/).

The following information is provided for management ofhighbush blueberry pests. If a pesticide is used, it must be registered withthe state and federal governments. Use Tables 5.1.2 (insecticides andmiticides), 5.1.3 (fungicides), 5.1.4 (herbicides) and 5.1.5 (other highbushblueberry pest management products) to determine legal pesticides, their brandnames, and any restrictions that may apply. Unless otherwise noted, use 100 galwater per acre. Always read the label before applying any pesticide.

**Table 5.1.1. Highbush blueberry pests and the associated stage of plant development.**
